image: docker:18-git

pipelines:
  default:
     - step:
         services:
           - docker
         script:
           - apk add --update bash coreutils tar
           - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
           - .industrial_ci/bitbucket.sh ROS_DISTRO=melodic UPSTREAM_WORKSPACE='github:nobleo/mobile_robot_simulator#fix/install'

definitions:
  services:
    docker:
      memory: 2048
